version: '3'
services:
  dbt-bq-dtc:
    build:
      context: .
      target: dbt-bigquery
    image: dbt/bigquery
    volumes:
      - .:/usr/app
      - ~/.dbt/:/root/.dbt/
      - ~/projects/auth/dtc-de-course-375114-5980d47b2e18.json:/.google/credentials/google_credentials.json
    network_mode: host
